#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Workspaces & Monitors ==================================#
bspc monitor -d I II III IV V VI VII VIII IX X

#Colors from .Xresources ================================#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

#Gaps and other configurations ==========================#
bspc config focused_border_color         "$BLUE" 
bspc config normal_border_color          "$BACKGROUND"
bspc config active_border_color          "$MAGENTA"
bspc config presel_feedback_color        "$GREEN"
bspc config border_width		  3
bspc config window_gap 			  6
bspc config focus_follows_pointer	  false
bspc config top_padding                   2
bspc config bottom_padding                28
bspc config split_ratio			  0.47
bspc config borderless_monocle	          true
bspc config gapless_monocle		  false
bspc config single_monocle		  true
bspc config focus_follows_pointer         true

#Application-Workspace Rules
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Nightly desktop='^2' follow=on
bspc rule -a mpv desktop='^5' state=fullscreen follow=on
bspc rule -a feh state=floating follow=on

#Autostart Apps =========================================#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager
~/.config/bspwm/scripts/autostart.sh
sxhkd &
#setting Wallpaper
bash $HOME/.fehbg

# Fix cursor
xsetroot -cursor_name left_ptr

#Scripts
#~/.config/bspwm/scripts/bspfloat &


