# bscalc
# Autogenerated from man page /usr/share/man/man1/bscalc.1
complete -c bscalc -s h -l help --description 'show this help message and exit.'
complete -c bscalc -l version --description 'show program\'s version number and exit.'
complete -c bscalc -s u -l unit --description 'Unit to show the result in.'
complete -c bscalc -s b -s B --description 'Show result in bytes.'
complete -c bscalc -s k -s K -l KiB --description 'Show result in KiB.'
complete -c bscalc -s m -s M -l MiB --description 'Show result in MiB.'
complete -c bscalc -s g -s G -l GiB --description 'Show result in GiB.'
complete -c bscalc -s t -s T -l TiB --description 'Show result in TiB.'
complete -c bscalc -s p -s P -l PiB --description 'Show result in PiB.'
complete -c bscalc -s e -s E -l EiB --description 'Show result in EiB.'
complete -c bscalc -l KB --description 'Show result in KB.'
complete -c bscalc -l MB --description 'Show result in MB.'
complete -c bscalc -l GB --description 'Show result in GB.'
complete -c bscalc -l TB --description 'Show result in TB.'
complete -c bscalc -l PB --description 'Show result in PB.'
complete -c bscalc -l EB --description 'Show result in EB.'

