# btrfs-send
# Autogenerated from man page /usr/share/man/man8/btrfs-send.8
complete -c btrfs-send -s e --description '.'
complete -c btrfs-send -s p --description '.'
complete -c btrfs-send -s c --description '.'
complete -c btrfs-send -s f --description '.'
complete -c btrfs-send -l no-data --description '.'
complete -c btrfs-send -s q --description 'option -v|--verbose:: (deprecated) alias for global.'
complete -c btrfs-send -s v --description 'option Global options.'
complete -c btrfs-send -l quiet --description '.'
complete -c btrfs-send -l verbose --description '.'

