# btrfs-rescue
# Autogenerated from man page /usr/share/man/man8/btrfs-rescue.8
complete -c btrfs-rescue -s y --description '.'
complete -c btrfs-rescue -s h --description '.'
complete -c btrfs-rescue -s v --description '.'

