# btrfs-scrub
# Autogenerated from man page /usr/share/man/man8/btrfs-scrub.8
complete -c btrfs-scrub -s c --description 'and.'
complete -c btrfs-scrub -s n --description 'options.  Note that not all IO schedulers honor the ionice settings.'
complete -c btrfs-scrub -s B --description '.'
complete -c btrfs-scrub -s d --description '.'
complete -c btrfs-scrub -s r --description '.'
complete -c btrfs-scrub -s R --description '.'
complete -c btrfs-scrub -s f --description '.'
complete -c btrfs-scrub -s q --description '.'

