# btrfs-device
# Autogenerated from man page /usr/share/man/man8/btrfs-device.8
complete -c btrfs-device -s K -l nodiscard --description '.'
complete -c btrfs-device -s f -l force --description '.'
complete -c btrfs-device -l all-devices --description 'or.'
complete -c btrfs-device -s d --description 'can be used as a fallback in case blkid is not available.'
complete -c btrfs-device -s u -l forget --description '.'
complete -c btrfs-device -s z -l reset --description '.'
complete -c btrfs-device -s c -l check --description '.'
complete -c btrfs-device -s b -l raw --description '.'
complete -c btrfs-device -s h -l human-readable --description '.'
complete -c btrfs-device -s H --description '.'
complete -c btrfs-device -l iec --description '.'
complete -c btrfs-device -l si --description '.'
complete -c btrfs-device -s k -l kbytes --description '.'
complete -c btrfs-device -s m -l mbytes --description '.'
complete -c btrfs-device -s g -l gbytes --description '.'
complete -c btrfs-device -s t -l tbytes --description '.'

