# clockdiff
# Autogenerated from man page /usr/share/man/man8/clockdiff.8
complete -c clockdiff -s o --description 'Use IP TIMESTAMP with ICMP ECHO instead of ICMP TIMESTAMP messages.'
complete -c clockdiff -o o1 --description 'Slightly different form of -o, namely it uses three-term IP TIMESTAMP with pr…'
complete -c clockdiff -s V --description 'Print version and exit.'

