# defrag
# Autogenerated from man page /usr/share/man/man8/defrag.f2fs.8
complete -c defrag -s s --description 'Specify the starting block address.'
complete -c defrag -s l --description 'Specifiy the number of blocks to move.'
complete -c defrag -s t --description 'Specify the destination block address.'
complete -c defrag -s i --description 'Set the direction to left.'
complete -c defrag -s d --description 'Specify the level of debugging options.'

