# devlink-sb
# Autogenerated from man page /usr/share/man/man8/devlink-sb.8
complete -c devlink-sb -s V --description '.'
complete -c devlink-sb -s n --description 'devlink sb show  [  DEV  [  sb SB_INDEX  ] ] devlink sb pool show  [  DEV  [ …'

