# doas
# Autogenerated from man page /usr/share/man/man1/doas.1
complete -c doas -s C --description 'Parse and check the configuration file config, then exit.'
complete -c doas -s L --description 'Clear any persisted authorizations from previous invocations, then immediatel…'
complete -c doas -s n --description 'Non interactive mode, fail if doas would prompt for password.'
complete -c doas -s s --description 'Execute the shell from SHELL or /etc/passwd.'
complete -c doas -s u --description 'Execute the command as user.  The default is root.'

