# dracut-catimages
# Autogenerated from man page /usr/share/man/man8/dracut-catimages.8
complete -c dracut-catimages -s f -l force --description 'overwrite existing initramfs file.'
complete -c dracut-catimages -s i -l imagedir --description 'Directory with additional images to add (default: /boot/dracut/).'
complete -c dracut-catimages -s o -l overlaydir --description 'Overlay directory, which contains additional files that will be used to creat…'
complete -c dracut-catimages -l nooverlay --description 'Do not use the overlay directory.'
complete -c dracut-catimages -l noimagedir --description 'Do not use the additional image directory.'
complete -c dracut-catimages -s h -l help --description 'display help text and exit.'
complete -c dracut-catimages -l debug --description 'output debug information of the build process.'
complete -c dracut-catimages -s v -l verbose --description 'verbose output during the build process.'

