# dump
# Autogenerated from man page /usr/share/man/man8/dump.f2fs.8
complete -c dump -s i --description 'Specify an inode number to dump out.'
complete -c dump -s n --description 'Specify a range presented by nids to dump NAT entries.'
complete -c dump -s s --description 'Specify a range presented by segment numbers to dump SIT entries.'
complete -c dump -s a --description 'Specify a range presented by segment numbers to dump SSA entries.'
complete -c dump -s b --description 'Specify a block address to retrieve its metadata information.'
complete -c dump -s d --description 'Specify the level of debugging options.'

