# elogind-inhibit
# Autogenerated from man page /usr/share/man/man1/elogind-inhibit.1
complete -c elogind-inhibit -l what --description 'Takes a colon-separated list of one or more operations to inhibit: "shutdown"…'
complete -c elogind-inhibit -l who --description 'Takes a short, human-readable descriptive string for the program taking the l…'
complete -c elogind-inhibit -l why --description 'Takes a short, human-readable descriptive string for the reason for taking th…'
complete -c elogind-inhibit -l mode --description 'Takes either "block" or "delay" and describes how the lock is applied.'
complete -c elogind-inhibit -l list --description 'Lists all active inhibition locks instead of acquiring one.'
complete -c elogind-inhibit -l no-pager --description 'Do not pipe output into a pager.'
complete -c elogind-inhibit -l no-legend --description 'Do not print the legend, i. e.  column headers and the footer with hints.'
complete -c elogind-inhibit -s h -l help --description 'Print a short help text and exit.'
complete -c elogind-inhibit -l version --description 'Print a short version string and exit.'

