# elogind
# Autogenerated from man page /usr/share/man/man8/elogind.8
complete -c elogind -s D -l daemon --description 'Daemonize elogind by double-forking into background.'
complete -c elogind -s h -l help --description 'Show the helpt text and exit.'

