# f2fs_io
# Autogenerated from man page /usr/share/man/man8/f2fs_io.8
complete -c f2fs_io -s d --description 'use direct I/O.'
complete -c f2fs_io -s m --description 'use mmap for source file.'
complete -c f2fs_io -s s --description 'use sendfile to transfer data get_cblocks [file] Get the number of compressed…'

