# git-maintenance
# Autogenerated from man page /usr/share/man/man1/git-maintenance.1
complete -c git-maintenance -l auto --description 'When combined with the run subcommand, run maintenance tasks only if certain …'
complete -c git-maintenance -l quiet --description 'Do not report progress or other information over stderr.'
complete -c git-maintenance -l task --description 'If this option is specified one or more times, then only run the specified ta…'

