# gpgrt-config
# Autogenerated from man page /usr/share/man/man1/gpgrt-config.1
complete -c gpgrt-config -l mt --description 'Provide output appropriate for multithreaded programs.'
complete -c gpgrt-config -l version --description 'Print the currently installed version of Libgpg-error on the standard output.'
complete -c gpgrt-config -l libs --description 'Print the linker flags that are necessary to link a program using Libgpg-erro…'
complete -c gpgrt-config -l cflags --description 'Print the compiler flags that are necessary to compile a program using Libgpg…'
complete -c gpgrt-config -l prefix --description 'If specified, use prefix instead of the installation prefix that Libgpg-error…'
complete -c gpgrt-config -l exec-prefix --description 'If specified, use prefix instead of the installation exec prefix that Libgpg-…'

