# groups
# Autogenerated from man page /usr/share/man/man1/groups.1
complete -c groups -l help --description 'display this help and exit.'
complete -c groups -l version --description 'output version information and exit AUTHOR Written by David MacKenzie and Jam…'

