# gtk-builder-convert
# Autogenerated from man page /usr/share/man/man1/gtk-builder-convert.1
complete -c gtk-builder-convert -l skip-windows -s w --description 'Convert everything but GtkWindow subclasses.'
complete -c gtk-builder-convert -l target-version -s t --description 'Some widgets and properties are different between GTK+ versions 2. 0 and 3.'
complete -c gtk-builder-convert -l root -s r --description 'Convert only the widget named name and its children.'

