# gtk-query-immodules-2
# Autogenerated from man page /usr/share/man/man1/gtk-query-immodules-2.0.1
complete -c gtk-query-immodules-2 -l update-cache --description 'Write the output to the default cache location instead of stdout.'

