# halt
# Autogenerated from man page /usr/share/man/man8/halt.8
complete -c halt -s n --description 'Don\'t sync before reboot or halt.'
complete -c halt -s f --description 'Force halt or reboot, don\'t call init 8.  This is dangerous !.'
complete -c halt -s d --description 'Do not write the wtmp record.'
complete -c halt -s w --description 'Just write the wtmp record.'
complete -c halt -s B --description 'Just write the wtmp record, but for a boot.'
complete -c halt -s h --description 'to put hard drives in standby mode.'
complete -c halt -s i --description 'to shut down network interfaces.'

