# hardlink
# Autogenerated from man page /usr/share/man/man1/hardlink.1
complete -c hardlink -s c -l content --description 'Compare only the contents of the files being considered for consolidation.'
complete -c hardlink -s f -l force --description 'Force hardlinking across file systems.'
complete -c hardlink -s n -l dry-run --description 'Do not perform the consolidation; only print what would be changed.'
complete -c hardlink -s v -l verbose --description 'Print summary after hardlinking.  The option may be specified more than once.'
complete -c hardlink -s x -l exclude --description 'Exclude files and directories matching pattern from hardlinking.'
complete -c hardlink -s h -l help --description 'Display help text and exit.'
complete -c hardlink -s V -l version --description 'Display version information and exit.'

