# hostname-coreutils
# Autogenerated from man page /usr/share/man/man1/hostname-coreutils.1
complete -c hostname-coreutils -l help --description 'display this help and exit.'
complete -c hostname-coreutils -l version --description 'output version information and exit AUTHOR Written by Jim Meyering.'

