# irqtop
# Autogenerated from man page /usr/share/man/man1/irqtop.1
complete -c irqtop -s o -l output --description 'Specify which output columns to print.'
complete -c irqtop -s d -l delay --description 'Update interrupt output every  seconds intervals.'
complete -c irqtop -s s -l sort --description 'Specify sort criteria by column name.'
complete -c irqtop -s V -l version --description 'Display version information and exit.'
complete -c irqtop -l help --description 'to get a list of all supported columns.'
complete -c irqtop -s h --description 'Display help text and exit.'

