# kbdinfo
# Autogenerated from man page /usr/share/man/man1/kbdinfo.1
complete -c kbdinfo -s C -l console --description 'the console device to be used;.'
complete -c kbdinfo -s V -l version --description 'print version number;.'
complete -c kbdinfo -s h -l help --description 'print this usage message.  AUTHORS Written by Alexey Gladkov.'

