# libinput-record
# Autogenerated from man page /usr/share/man/man1/libinput-record.1
complete -c libinput-record -l help --description 'Print help.'
complete -c libinput-record -l all --description 'Record all /dev/input/event* devices available on the system.'
complete -c libinput-record -l autorestart --description 'Terminate the current recording after  s seconds of device inactivity.'
complete -c libinput-record -l output-file --description 'Specifies the output file to use.'
complete -c libinput-record -l show-keycodes --description 'Show keycodes as-is in the recording.'
complete -c libinput-record -s o --description '.'
complete -c libinput-record -l with-libinput --description 'Record libinput events alongside device events.  THIS FEATURE IS EXPERIMENTAL.'
complete -c libinput-record -l multiple --description '.'

