# libinput-measure-touchpad-size
# Autogenerated from man page /usr/share/man/man1/libinput-measure-touchpad-size.1
complete -c libinput-measure-touchpad-size -l help --description 'Print help LIBINPUT Part of the libinput(1) suite.'

