# libinput-analyze
# Autogenerated from man page /usr/share/man/man1/libinput-analyze.1
complete -c libinput-analyze -l help --description 'Print help FEATURES Features that can be analyzed include.'

