# libinput-quirks-list
# Autogenerated from man page /usr/share/man/man1/libinput-quirks-list.1
complete -c libinput-quirks-list -l data-dir --description 'Use the given directory as data directory for quirks files.'
complete -c libinput-quirks-list -l help --description 'Print help.'
complete -c libinput-quirks-list -l verbose --description 'Use verbose output, useful for debugging.'

