# libinput-measure
# Autogenerated from man page /usr/share/man/man1/libinput-measure.1
complete -c libinput-measure -l help --description 'Print help FEATURES Features that can be measured include.'

