# libinput-quirks-validate
# Autogenerated from man page /usr/share/man/man1/libinput-quirks-validate.1
complete -c libinput-quirks-validate -l data-dir --description 'Use the given directory as data directory for quirks files.'
complete -c libinput-quirks-validate -l help --description 'Print help.'
complete -c libinput-quirks-validate -l verbose --description 'Use verbose output, useful for debugging.'

