# libinput-analyze-per-slot-delta
# Autogenerated from man page /usr/share/man/man1/libinput-analyze-per-slot-delta.1
complete -c libinput-analyze-per-slot-delta -l help --description 'Print help.'
complete -c libinput-analyze-per-slot-delta -l ignore-below --description 'Ignore any movement below the given threshold.'
complete -c libinput-analyze-per-slot-delta -l threshold --description 'Color any movement above this threshold in red.'
complete -c libinput-analyze-per-slot-delta -l use-mm --description 'Print data in mm instead of device units.'
complete -c libinput-analyze-per-slot-delta -l use-st --description 'Use the single-touch ABS_X/ABS_Y instead of the multitouch axes.'
complete -c libinput-analyze-per-slot-delta -l use-absolute --description 'Print absolute coordinates, not deltas OUTPUT An example output for a single …'
complete -c libinput-analyze-per-slot-delta -l ---- --description 'indicates the finger has lifted.'

