# lsirq
# Autogenerated from man page /usr/share/man/man1/lsirq.1
complete -c lsirq -s n -l noheadings --description 'Don\'t print headings.'
complete -c lsirq -s o -l output --description 'Specify which output columns to print.'
complete -c lsirq -s s -l sort --description 'Specify sort criteria by column name.'
complete -c lsirq -s J -l json --description 'Use JSON output format.'
complete -c lsirq -s P -l pairs --description 'Produce output in the form of key="value" pairs.'
complete -c lsirq -s V -l version --description 'Display version information and exit.'
complete -c lsirq -l help --description 'to get a list of all supported columns.'
complete -c lsirq -s h --description 'Display help text and exit.  AUTHORS.'

