# makewhatis
# Autogenerated from man page /usr/share/man/man8/makewhatis.8
complete -c makewhatis -s a --description 'Use all directories and files found below dir .'
complete -c makewhatis -s C --description 'Specify an alternative configuration file in man. conf 5 format.'
complete -c makewhatis -s D --description 'Display all files added or removed to the index.'
complete -c makewhatis -s d --description 'Merge (remove and re-add) Ar to the database in dir.'
complete -c makewhatis -s n --description 'Do not create or modify any database; scan and parse only, and print manual p…'
complete -c makewhatis -s p --description 'Print warnings about potential problems with manual pages to the standard err…'
complete -c makewhatis -s Q --description 'Quickly build reduced-size databases by reading only the NAME sections of man…'
complete -c makewhatis -s T --description 'Use UTF-8 encoding instead of ASCII for strings stored in the databases.'
complete -c makewhatis -s t --description 'Check the given files for potential problems.  Implies a, n, and p.'
complete -c makewhatis -s u --description 'Remove Ar from the database in dir.'

