# man
# Autogenerated from man page /usr/share/man/man1/man.1
complete -c man -s a --description 'Display all matching manual pages.'
complete -c man -s C --description 'Use the specified file instead of the default configuration file.'
complete -c man -s c --description 'Copy the manual page to the standard output instead of using less 1 to pagina…'
complete -c man -s f --description 'A synonym for whatis 1.'
complete -c man -s h --description 'Display only the SYNOPSIS lines of the requested manual pages.'
complete -c man -s k --description 'A synonym for apropos 1.'
complete -c man -s l --description 'A synonym for mandoc 1.  The name arguments are interpreted as filenames.'
complete -c man -s M --description 'Override the list of standard directories which man searches for manual pages.'
complete -c man -s m --description 'Augment the list of standard directories which man searches for manual pages.'
complete -c man -s S --description 'Only show pages for the specified machine 1 architecture.'
complete -c man -s w --description 'List the pathnames of all matching manual pages instead of displaying any of …'

