# mandoc-apropos
# Autogenerated from man page /usr/share/man/man1/mandoc-apropos.1
complete -c mandoc-apropos -s a --description 'Instead of showing only the title lines, show the complete manual pages, just…'
complete -c mandoc-apropos -s C --description 'Specify an alternative configuration file in man. conf 5 format.'
complete -c mandoc-apropos -s f --description 'Search for all words in expression in manual page names only.'
complete -c mandoc-apropos -s k --description 'Support the full expression syntax.  It is the default for mandoc-apropos.'
complete -c mandoc-apropos -s M --description 'Use the colon-separated path instead of the default list of paths searched fo…'
complete -c mandoc-apropos -s m --description 'Prepend the colon-separated paths to the list of paths searched for makewhati…'
complete -c mandoc-apropos -s O --description 'Show the values associated with the key outkey instead of the manual descript…'
complete -c mandoc-apropos -s S --description 'Restrict the search to pages for the specified machine 1 architecture.'
complete -c mandoc-apropos -s s --description 'Restrict the search to the specified section of the manual.'
complete -c mandoc-apropos -s i --description 'If term is a regular expression, it is evaluated case-insensitively.'

