# mandoc
# Autogenerated from man page /usr/share/man/man1/mandoc.1
complete -c mandoc -s a --description 'If the standard output is a terminal device and c is not specified, use less …'
complete -c mandoc -s c --description 'Copy the formatted manual pages to the standard output without using less 1 t…'
complete -c mandoc -s I --description 'Override the default operating system name for the mdoc 7 \\&Os and for the ma…'
complete -c mandoc -s K --description 'Specify the input encoding.'
complete -c mandoc -o mdoc --description 'With mdoc, all input files are interpreted as mdoc 7.'
complete -c mandoc -s O --description 'Comma-separated output options.'
complete -c mandoc -s T --description 'Select the output format.'
complete -c mandoc -s W --description 'Specify the minimum message level to be reported on the standard error output…'

