# mandoc-soelim
# Autogenerated from man page /usr/share/man/man1/mandoc-soelim.1
complete -c mandoc-soelim -s C --description 'Recognise . so when not followed by a space character.'
complete -c mandoc-soelim -s r --description 'Compatibility with GNU groff\'s mandoc-soelim soelim (does nothing).'
complete -c mandoc-soelim -s t --description 'Compatibility with GNU groff\'s mandoc-soelim soelim (does nothing).'
complete -c mandoc-soelim -s v --description 'Compatibility with GNU groff\'s mandoc-soelim soelim (does nothing).'
complete -c mandoc-soelim -s I --description 'This option specify directories where mandoc-soelim searches for files (both …'

