# modules-load
# Autogenerated from man page /usr/share/man/man8/modules-load.8
complete -c modules-load -s n --description 'dry-run mode.'
complete -c modules-load -s v --description 'verbose mode.  Print messages about what the program is doing.'

