# mpd
# Autogenerated from man page /usr/share/man/man1/mpd.1
complete -c mpd -l help --description 'Output a brief help message.'
complete -c mpd -l kill --description 'Kill the currently running mpd session.'
complete -c mpd -l no-config --description 'Don\\(aqt read from the configuration file.'
complete -c mpd -l no-daemon --description 'Don\\(aqt detach from console.'
complete -c mpd -l stderr --description 'Print messages to stderr.'
complete -c mpd -l verbose --description 'Verbose logging.'
complete -c mpd -l version --description 'Print version information.'

