# ncmpcpp
# Autogenerated from man page /usr/share/man/man1/ncmpcpp.1
complete -c ncmpcpp -s h -l host --description 'Connect to server at host [localhost].'
complete -c ncmpcpp -s p -l port --description 'Connect to server at port [6600].'
complete -c ncmpcpp -l current-song --description 'Print current song using given format and exit.'
complete -c ncmpcpp -s c -l config --description 'Specify configuration file(s).'
complete -c ncmpcpp -l ignore-config-errors --description 'Ignore unknown and invalid options in configuration files.'
complete -c ncmpcpp -l bindings --description 'Specify bindings file(s).'
complete -c ncmpcpp -s s -l screen --description 'Specify the startup screen (<name> may be: help, playlist, browser, search_en…'
complete -c ncmpcpp -s S -l slave-screen --description 'Specify the startup slave screen (<name> may be: help, playlist, browser, sea…'
complete -c ncmpcpp -s q -l quiet --description 'Suppress logs and excess output.'
complete -c ncmpcpp -s '?' -l help --description 'Display help.'

