# newsboat
# Autogenerated from man page /usr/share/man/man1/newsboat.1
complete -c newsboat -s h -l help --description '.'
complete -c newsboat -s r -l refresh-on-start --description '.'
complete -c newsboat -s e -l export-to-opml --description '.'
complete -c newsboat -s X -l vacuum --description '.'
complete -c newsboat -s v -s V -l version --description '.'
complete -c newsboat -s i -l import-from-opml --description '.'
complete -c newsboat -s u -l url-file --description '.'
complete -c newsboat -s c -l cache-file --description '.'
complete -c newsboat -s C -l config-file --description '.'
complete -c newsboat -s x -l execute --description '.'
complete -c newsboat -s l -l log-level --description '.'
complete -c newsboat -s d -l log-file --description '.'
complete -c newsboat -s E -l export-to-file --description '.'
complete -c newsboat -s I -l import-from-file --description '.'

