# nfs-ls
# Autogenerated from man page /usr/share/man/man1/nfs-ls.1
complete -c nfs-ls -s s -l summary --description 'Print a summary line at the end of output.'
complete -c nfs-ls -s R -l recursive --description 'Recursive listing of the specified URL.'
complete -c nfs-ls -s D -l 'discovery;' --description 'This option is used to discover local NFS servers and to list the exports for…'
complete -c nfs-ls -s '?' -l help --description 'Display basic help text.'
complete -c nfs-ls -l usage --description 'Display basic usage text.'
complete -c nfs-ls -o rwxrwxr-x --description '.'
complete -c nfs-ls -o rwxr-xr-x --description '.'
complete -c nfs-ls -o rwxrwxrwx --description '       OPTIONS.'

