# nologin
# Autogenerated from man page /usr/share/man/man8/nologin.8
complete -c nologin -s h -l help --description 'Display help text and exit.'
complete -c nologin -s c -l command --description '.'
complete -c nologin -l init-file --description '.'
complete -c nologin -s i -l interactive --description '.'
complete -c nologin -s l -l login --description '.'
complete -c nologin -l noprofile --description '.'
complete -c nologin -l norc --description '.'
complete -c nologin -l posix --description '.'
complete -c nologin -l rcfile --description '.'
complete -c nologin -s r -l restricted --description 'These shell command-line options are ignored to avoid nologin error.'
complete -c nologin -s V -l version --description 'Display version information and exit.'

