# ocspcheck
# Autogenerated from man page /usr/share/man/man8/ocspcheck.8
complete -c ocspcheck -s C --description 'Specify a PEM format root certificate bundle to use for the validation of req…'
complete -c ocspcheck -s i --description 'Specify an input filename from which a DER-encoded OCSP response will be read…'
complete -c ocspcheck -s N --description 'Do not use a nonce value in the OCSP request, or validate that the nonce was …'
complete -c ocspcheck -s o --description 'Specify an output filename where the DER encoded response from the OCSP serve…'
complete -c ocspcheck -s v --description 'Increase verbosity.'

