# pcmanfm
# Autogenerated from man page /usr/share/man/man1/pcmanfm.1
complete -c pcmanfm -s d -l daemon-mode --description 'run PCManFM as a daemon (ignored if another PCManFM is already running).'
complete -c pcmanfm -s p -l profile --description 'load another configuration profile instead of "default".'
complete -c pcmanfm -l no-desktop --description 'for Nautilus compatibility . PP . SS Per-instance options:.'
complete -c pcmanfm -l desktop --description 'launch desktop manager (ignores -d).'
complete -c pcmanfm -l desktop-off --description 'turn off desktop manager if it\'s running.'
complete -c pcmanfm -l desktop-pref --description 'open desktop preference dialog.'
complete -c pcmanfm -l one-screen --description 'manage desktop only on current X screen (only if --desktop is used).'
complete -c pcmanfm -s n -l new-win --description 'open directories in new window.'
complete -c pcmanfm -l role --description 'set X role for window (only if -n is used).'
complete -c pcmanfm -l wallpaper-mode --description 'Set mode of desktop wallpaper, mode is:  color (fill with solid color),  stre…'
complete -c pcmanfm -s w -l set-wallpaper --description 'set desktop wallpaper from image file.'
complete -c pcmanfm -l show-pref --description 'open preferences dialog on page n.'
complete -c pcmanfm -s f -l find-files --description 'open a file search dialog window.'

