# pfbtops
# Autogenerated from man page /usr/share/man/man1/pfbtops.1
complete -c pfbtops -l help --description 'Display a usage message and exit.'
complete -c pfbtops -s v --description '.'
complete -c pfbtops -l version --description 'Display version information and exit.  SEE ALSO grops (1), gropdf (1).'

