# podboat
# Autogenerated from man page /usr/share/man/man1/podboat.1
complete -c podboat -s h -l help --description '.'
complete -c podboat -s C -l config-file --description '.'
complete -c podboat -s q -l queue-file --description '.'
complete -c podboat -s a -l autodownload --description '.'
complete -c podboat -s l -l log-level --description '.'
complete -c podboat -s d -l log-file --description '.'

