# poweroff
# Autogenerated from man page /usr/share/man/man8/poweroff.8
complete -c poweroff -s n --description 'Don\'t sync before reboot or halt.'
complete -c poweroff -s f --description 'Force halt or reboot, don\'t call init 8.  This is dangerous !.'
complete -c poweroff -s d --description 'Do not write the wtmp record.'
complete -c poweroff -s w --description 'Just write the wtmp record.'
complete -c poweroff -s B --description 'Just write the wtmp record, but for a boot.'
complete -c poweroff -s h --description 'to put hard drives in standby mode.'
complete -c poweroff -s i --description 'to shut down network interfaces.'

