# reboot
# Autogenerated from man page /usr/share/man/man8/reboot.8
complete -c reboot -s n --description 'Don\'t sync before reboot or halt.'
complete -c reboot -s f --description 'Force halt or reboot, don\'t call init 8.  This is dangerous !.'
complete -c reboot -s d --description 'Do not write the wtmp record.'
complete -c reboot -s w --description 'Just write the wtmp record.'
complete -c reboot -s B --description 'Just write the wtmp record, but for a boot.'
complete -c reboot -s h --description 'to put hard drives in standby mode.'
complete -c reboot -s i --description 'to shut down network interfaces.'

