# sfconvert
# Autogenerated from man page /usr/share/man/man1/sfconvert.1
complete -c sfconvert -l help -s h --description 'Print help message.'
complete -c sfconvert -l version -s v --description 'Print version information.'

