# sfinfo
# Autogenerated from man page /usr/share/man/man1/sfinfo.1
complete -c sfinfo -l short -s s --description 'Print short single-line summary of each recognized audio file.'
complete -c sfinfo -l reporterror -s r --description 'Print an error message if any of the specified files are not recognized as va…'
complete -c sfinfo -l help -s h --description 'Print help message.'
complete -c sfinfo -l version -s v --description 'Print version information.'

