# shutdown
# Autogenerated from man page /usr/share/man/man8/shutdown.8
complete -c shutdown -s c --description 'Cancel an ongoing shutdown.'
complete -c shutdown -s f --description 'Enable fast booting; skip fsck 8 on next boot.'
complete -c shutdown -s F --description 'Force run of fsck 8 on next boot.'
complete -c shutdown -s h --description 'Halt the system.'
complete -c shutdown -s k --description 'Don\'t really shutdown; only send the warning messages to everybody.'
complete -c shutdown -s P --description 'Poweroff the system.'
complete -c shutdown -s r --description 'Reboot the system.  now Shutdown without further waiting.'
complete -c shutdown -s t --description 'to wait secs seconds between SIGKILL and SIGTERM on shutdown is silently igno…'
complete -c shutdown -s a --description 'Use /etc/shutdown. allow.'
complete -c shutdown -s H --description 'Drop into boot monitor.'
complete -c shutdown -s n --description 'Don\'t call init 8.'

