# slim
# Autogenerated from man page /usr/share/man/man1/slim.1
complete -c slim -s d --description 'run as a daemon.'
complete -c slim -s p --description 'display a preview of the theme.'
complete -c slim -s h --description 'display a brief help message.'
complete -c slim -s v --description 'display version information EXAMPLES slim -d run slim in daemon mode slim -p …'

