# st
# Autogenerated from man page /usr/share/man/man1/st.1
complete -c st -s a --description 'disable alternate screens in terminal.'
complete -c st -s c --description 'defines the window class (default $TERM).'
complete -c st -s f --description 'defines the  font to use when st is run.'
complete -c st -s g --description 'defines the X11 geometry string.'
complete -c st -s i --description 'will fixate the position given with the -g option.'
complete -c st -s n --description 'defines the window instance name (default $TERM).'
complete -c st -s o --description 'writes all the I/O to  iofile.'
complete -c st -s T --description 'defines the window title (default \'st\').'
complete -c st -s t --description 'defines the window title (default \'st\').'
complete -c st -s w --description 'embeds st within the window identified by  windowid.'
complete -c st -s l --description 'use a tty  line instead of a pseudo terminal.'
complete -c st -s v --description 'prints version information to stderr, then exits.'
complete -c st -s e --description 'st executes command instead of the shell.'

