# sv
# Autogenerated from man page /usr/share/man/man8/sv.8
complete -c sv -s v --description 'If the  command is up, down, term, once, cont, or exit, then wait up to 7 sec…'
complete -c sv -s w --description 'Override the default timeout of 7 seconds with sec seconds.'

