# sxhkd
# Autogenerated from man page /usr/share/man/man1/sxhkd.1
complete -c sxhkd -s h --description 'Print the synopsis to standard output and exit.'
complete -c sxhkd -s v --description 'Print the version information to standard output and exit.'
complete -c sxhkd -s m --description 'Handle the first COUNT mapping notify events.'
complete -c sxhkd -s t --description 'Timeout in seconds for the recording of chord chains.'
complete -c sxhkd -s c --description 'Read the main configuration from the given file.'
complete -c sxhkd -s r --description 'Redirect the commands output to the given file.'
complete -c sxhkd -s s --description 'Output status information to the given FIFO.'
complete -c sxhkd -s a --description 'Name of the keysym used for aborting chord chains.'

