# uchardet
# Autogenerated from man page /usr/share/man/man1/uchardet.1
complete -c uchardet -s v --description 'Print version and build information.'
complete -c uchardet -s h --description 'Print help text.  uchardet Command Line Interface.'

