# udevd
# Autogenerated from man page /usr/share/man/man8/udevd.8
complete -c udevd -s d -l daemon --description 'Detach and run in the background.'
complete -c udevd -s D -l debug --description 'Print debug messages to standard error.'
complete -c udevd -s c -l children-max --description 'Limit the number of events executed in parallel.'
complete -c udevd -s e -l exec-delay --description 'Delay the execution of RUN instructions by the given number of seconds.'
complete -c udevd -s t -l event-timeout --description 'Set the number of seconds to wait for events to finish.'
complete -c udevd -s N -l resolve-names --description 'Specify when udevd should resolve names of users and groups.'
complete -c udevd -s h -l help --description '.'

