# vi
# Autogenerated from man page /usr/share/man/man1/vi.1
complete -c vi -s c --description 'Execute  cmd immediately after starting the edit session.'
complete -c vi -s e --description 'Start editing in ex mode, as if the command name were R ex .'
complete -c vi -s l --description 'Start editing with the lisp and showmatch options set.'
complete -c vi -s R --description 'Start editing in read\\(hyonly mode, as if the command name was R view , or th…'
complete -c vi -s r --description 'Recover the specified files, or, if no files are specified, list the files th…'
complete -c vi -s S --description 'Run with the  secure edit option set, disallowing all access to external prog…'
complete -c vi -s s --description 'Enter batch mode; applicable only to  ex edit sessions.'
complete -c vi -s t --description 'Start editing at the specified tag.  (See R ctags (1)).'
complete -c vi -s w --description 'Set the initial window size to the specified number of lines.'
complete -c vi -s v --description 'Start editing in vi mode, as if the command name was vi or view .'

