# vlogger
# Autogenerated from man page /usr/share/man/man8/vlogger.8
complete -c vlogger -s f --description 'Read lines from the specified file.'
complete -c vlogger -s i --description 'Log the PID of the vlogger process.  Only supported if syslog 3 is used.'
complete -c vlogger -s p --description 'The.  pri can be facility. level or just facility.'
complete -c vlogger -s S --description 'Force vlogger to use syslog 3 even if /etc/vlogger exists.'
complete -c vlogger -s s --description 'Output the message to standard error, as well as syslog 3.'
complete -c vlogger -s t --description 'Defines the openlog 3 ident which is used as prefix for each log message or p…'

