# xbps-digest
# Autogenerated from man page /usr/share/man/man1/xbps-digest.1
complete -c xbps-digest -s m --description 'Sets the message digest mode.  Supported: sha256.'
complete -c xbps-digest -s h --description 'Show the help message.'
complete -c xbps-digest -s V --description 'Show the version information.'

