# xbps-fbulk
# Autogenerated from man page /usr/share/man/man1/xbps-fbulk.1
complete -c xbps-fbulk -s a --description 'Set a different target architecture, useful for cross compiling.'
complete -c xbps-fbulk -s j --description 'Set number of parallel builds running at the same time.  By default set to 1.'
complete -c xbps-fbulk -s l --description 'Set the log directory.  By default set to `log. <pid>`.'
complete -c xbps-fbulk -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-fbulk -s h --description 'Show the help message.'
complete -c xbps-fbulk -s v --description 'Enables verbose messages.'
complete -c xbps-fbulk -s V --description 'Show the version information.'

