# xbps-uchroot
# Autogenerated from man page /usr/share/man/man1/xbps-uchroot.1
complete -c xbps-uchroot -s b --description 'Bind mounts src into CHROOTDIR/dest.'
complete -c xbps-uchroot -s O --description 'Setups a temporary directory and then creates an overlay layer (via overlayfs…'
complete -c xbps-uchroot -s o --description 'Arguments passed to the tmpfs mount, if the O and t options are specified.'
complete -c xbps-uchroot -s t --description 'This makes the temporary directory to be mounted in tmpfs, so that everything…'

