# xbps-pkgdb
# Autogenerated from man page /usr/share/man/man1/xbps-pkgdb.1
complete -c xbps-pkgdb -s a --description 'Process all registered packages, regardless of its state.'
complete -c xbps-pkgdb -s C --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-pkgdb -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-pkgdb -s h --description 'Show the help message.'
complete -c xbps-pkgdb -s m --description '-tag -width -x auto , manual auto No marks each Ar PKGNAME as automatic - as …'
complete -c xbps-pkgdb -s r --description 'Specifies a full path for the target root directory.'
complete -c xbps-pkgdb -s u --description 'Updates the pkgdb format to the latest version making the necessary conversio…'
complete -c xbps-pkgdb -s v --description 'Enables verbose messages.'
complete -c xbps-pkgdb -s V --description 'Show the version information.  El FILES -tag -width /var/db/xbps/.'

