# xbps-checkvers
# Autogenerated from man page /usr/share/man/man1/xbps-checkvers.1
complete -c xbps-checkvers -s C --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-checkvers -s D --description 'Specifies a full path to the void-packages repository.'
complete -c xbps-checkvers -s e --description 'List packages present in repos, but not in distdir.'
complete -c xbps-checkvers -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-checkvers -s f --description 'Format according to the string format, inspired by printf 3.'
complete -c xbps-checkvers -s h --description 'Show the help message.'
complete -c xbps-checkvers -s i --description 'Ignore repositories defined in configuration files.'
complete -c xbps-checkvers -s I --description 'Check for outdated installed packages rather than in repositories.'
complete -c xbps-checkvers -s m --description 'Only process listed files.'
complete -c xbps-checkvers -s R --description 'Repository to be added to the top of the list.'
complete -c xbps-checkvers -s r --description 'Specifies a full path for the target root directory.'
complete -c xbps-checkvers -s s --description 'List all packages found in the xbps-checkvers void-packages tree and prints v…'
complete -c xbps-checkvers -s V --description 'Show the version information.'

