# xbps-fetch
# Autogenerated from man page /usr/share/man/man1/xbps-fetch.1
complete -c xbps-fetch -s d --description 'Enables debug messages on stderr.'
complete -c xbps-fetch -s h --description 'Show the help message.'
complete -c xbps-fetch -s o --description 'Rename file from specified URL to output.'
complete -c xbps-fetch -s v --description 'Enables verbose messages.'
complete -c xbps-fetch -s s --description 'Print sha256sums of downloaded files.'
complete -c xbps-fetch -s V --description 'Show the version information.'

