# xbps-alternatives
# Autogenerated from man page /usr/share/man/man1/xbps-alternatives.1
complete -c xbps-alternatives -s C --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-alternatives -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-alternatives -s g --description 'Alternative group name to match.  To be used with the set mode.'
complete -c xbps-alternatives -s h --description 'Show the help message.'
complete -c xbps-alternatives -s r --description 'Specifies a full path for the target root directory.'
complete -c xbps-alternatives -s v --description 'Enables verbose messages.'
complete -c xbps-alternatives -s V --description 'Show the version information.'
complete -c xbps-alternatives -s l --description 'Lists all current alternative groups or only from PKG, or just a specific gro…'
complete -c xbps-alternatives -s s --description 'Set alternative groups specified by PKG or just a specific group, if the g Fl…'

