# xbps-reconfigure
# Autogenerated from man page /usr/share/man/man1/xbps-reconfigure.1
complete -c xbps-reconfigure -s a --description 'Configures all packages.'
complete -c xbps-reconfigure -s C --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-reconfigure -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-reconfigure -s f --description 'Forcefully reconfigure package even if it was configured previously.'
complete -c xbps-reconfigure -s h --description 'Show the help message.'
complete -c xbps-reconfigure -s i --description 'Ignore PKG when configuring all packages with a, Fl -all.'
complete -c xbps-reconfigure -s r --description 'Specifies a path for the target root directory.'
complete -c xbps-reconfigure -s v --description 'Enables verbose messages.'
complete -c xbps-reconfigure -s V --description 'Show the version information.  El FILES -tag -width /var/db/xbps/.'

