# xbps-remove
# Autogenerated from man page /usr/share/man/man1/xbps-remove.1
complete -c xbps-remove -s C --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-remove -s c --description 'Specifies a path to the cache directory, where binary packages are stored.'
complete -c xbps-remove -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-remove -s F --description 'Forcefully remove package even if there are reverse dependencies and/or broke…'
complete -c xbps-remove -s f --description 'Forcefully remove package files even if they have been modified.'
complete -c xbps-remove -s h --description 'Show the help message.'
complete -c xbps-remove -s n --description 'Dry-run mode.  Show what actions would be done but don\'t do anything.'
complete -c xbps-remove -s O --description 'Cleans cache directory removing obsolete binary packages.'
complete -c xbps-remove -s o --description 'Removes installed package orphans that were installed automatically (as depen…'
complete -c xbps-remove -s R --description 'Recursively remove packages that were installed by PKGNAME and aren\'t require…'
complete -c xbps-remove -s r --description 'Specifies a full path for the target root directory.'
complete -c xbps-remove -s v --description 'Enables verbose messages.'
complete -c xbps-remove -s y --description 'Assume yes to all questions and avoid interactive questions.'
complete -c xbps-remove -s V --description 'Show the version information.  El FILES -tag -width /var/db/xbps/.'

