# xbps-dgraph
# Autogenerated from man page /usr/share/man/man1/xbps-dgraph.1
complete -c xbps-dgraph -s C --description 'Specifies a path to the XBPS configuration directory.'
complete -c xbps-dgraph -s c --description 'Specifies a path to the graph configuration file, to modify the settings of t…'
complete -c xbps-dgraph -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-dgraph -s h --description 'Show the help message.'
complete -c xbps-dgraph -s M --description 'For remote repositories, the data is fetched and stored in memory for the cur…'
complete -c xbps-dgraph -s R --description 'Enable repository mode.'
complete -c xbps-dgraph -s r --description 'Specifies a full path for the target root directory.'
complete -c xbps-dgraph -s V --description 'Show the version information.'
complete -c xbps-dgraph -s g --description 'Generates a graph configuration file in the current working directory.'
complete -c xbps-dgraph -s f --description 'Generates a full dependency graph of the target package.'
complete -c xbps-dgraph -s m --description 'Generates a metadata graph of the target package.'

