# xbps-rindex
# Autogenerated from man page /usr/share/man/man1/xbps-rindex.1
complete -c xbps-rindex -s d --description 'Enables extra debugging shown to stderr.'
complete -c xbps-rindex -l compression --description 'Set the repodata compression format.  If unset, defaults to zstd.'
complete -c xbps-rindex -s C --description 'Check not only for file existence but for the correct file hash while cleanin…'
complete -c xbps-rindex -s f --description 'Forcefully register binary package into the local repository, overwriting exi…'
complete -c xbps-rindex -s h --description 'Show the help message.'
complete -c xbps-rindex -s V --description 'Show the version information.'

