# zzz
# Autogenerated from man page /usr/share/man/man8/zzz.8
complete -c zzz -s n --description 'dry-run mode.'
complete -c zzz -s S --description 'Enter low-power idle mode (ACPI S0, kernel name "freeze").'
complete -c zzz -s z --description 'Enter suspend to RAM mode (ACPI S3, kernel name "mem").'
complete -c zzz -s Z --description 'Enter hibernate to disk mode (ACPI S4, kernel name "disk") and power off.'
complete -c zzz -s R --description 'Enter hibernate to disk mode and reboot.'
complete -c zzz -s H --description 'Enter hibernate to disk mode and suspend.'

